[package]
name = "whisper"
version = "0.1.3"
authors = ["Xavier Lange <xrlange@gmail.com>"]
description = "Whisper time series file support"
license = "MIT"
homepage = "https://www.github.com/tureus/graphite-rust"
repository = "https://github.com/tureus/whisper.git"

[dependencies.memmap]

[[bin]]
name="mapit"

[dependencies]
byteorder = "*"